#!/usr/bin/env python3
"""Offline tests for the council's analysis tools (stdlib unittest; no network, no model calls).

Usage: test_ptools.py [-v]
Run directly, or through scripts/test-completion.sh which also exercises both tools
against a run directory generated by council.sh itself.
"""
import importlib.util
import io
import json
import os
import shutil
import subprocess
import sys
import tempfile
import unittest
from contextlib import redirect_stdout
from pathlib import Path

HERE = Path(__file__).resolve().parent


def load(name):
    spec = importlib.util.spec_from_file_location(name, HERE / (name + ".py"))
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


dedup_check = load("dedup_check")
prompt_report = load("prompt_report")

EM = "—"  # the em dash council.sh puts in every task header
TAIL_RULE = "Nothing may follow the JSON tail.\n"


def prompt_round_n(task, rnd, candidate_id, candidate, relayed, answers_block="", rules=False):
    """Reproduce the shape council.sh prompt_roundN() emits, for section accounting."""
    out = ""
    if rules:
        out += "You are member A of a council of 3 AI agents.\n...rules...\n" + TAIL_RULE + "\n"
    out += "=== TASK {} {} round {} of 4 ===\n".format(task, EM, rnd)
    out += "Candidate for this round {} proposed by member A. Vote on this EXACT text:\n".format(EM)
    out += "<<<CANDIDATE {}\n{}\n>>>\n\n".format(candidate_id, candidate)
    out += "Posts of the other members in round {}:\n".format(rnd - 1)
    for member, body in relayed:
        out += "--- member {} ---\n{}\n\n".format(member, body)
    if not relayed:
        out += "\n"
    out += answers_block
    out += "Your job this round: reply to the other members.\n"
    return out.encode()


def filler(tag, n):
    """Padding with no internal repeat >= MIN_BYTES, so fixtures test only what they plant."""
    out = []
    while sum(len(x) for x in out) < n:
        out.append("{}-{:06d}-".format(tag, len(out)))
    return "".join(out)[:n]


def post(proposal, prose="Prose."):
    tail = json.dumps({"vote": "propose", "proposal": proposal, "questions": []})
    return "{}\n```json\n{}\n```".format(prose, tail), tail


def make_run(tmp, prompts, state):
    run = Path(tmp)
    (run / "prompts").mkdir(parents=True, exist_ok=True)
    (run / "posts").mkdir(parents=True, exist_ok=True)
    for name, data in prompts.items():
        (run / "prompts" / name).write_bytes(data)
    (run / "state.json").write_text(json.dumps(state))
    return run


def run_cli(script, *args):
    proc = subprocess.run([sys.executable, str(HERE / script)] + [str(a) for a in args],
                          capture_output=True, text=True)
    return proc.returncode, proc.stdout, proc.stderr


def planted(blocks, block, times):
    """The tool reports MAXIMAL repeats, so a planted block may be reported with
    the identical bytes that happen to surround every occurrence. Assert containment."""
    hits = [(b, offs) for b, offs in blocks if block.encode() in b and len(offs) == times]
    return hits


def tree_fingerprint(root):
    out = {}
    for path in sorted(Path(root).rglob("*")):
        if path.is_file():
            out[str(path.relative_to(root))] = path.read_bytes()
    return out


class DedupBlocks(unittest.TestCase):
    """dedup_check.repeated_blocks: the byte-level duplicate finder."""

    def test_empty_input_is_handled(self):
        self.assertEqual(dedup_check.repeated_blocks(b""), [])

    def test_unique_text_has_no_repeats(self):
        data = ("".join("line %04d unique content here\n" % i for i in range(200))).encode()
        self.assertEqual(dedup_check.repeated_blocks(data), [])

    def test_repeat_at_threshold_is_found_with_offsets(self):
        block = ("R" * 100 + "-tail-of-the-repeated-block-0123456789abcdef")[:dedup_check.MIN_BYTES]
        self.assertEqual(len(block), 128)
        data = (filler("A", 300) + block + filler("B", 300) + block + filler("C", 300)).encode()
        blocks = dedup_check.repeated_blocks(data)
        hits = planted(blocks, block, 2)
        self.assertEqual(len(hits), 1, blocks)
        reported, offsets = hits[0]
        self.assertEqual(offsets[1] - offsets[0], len(block) + 300,
                         "the two planted copies are 300 filler bytes apart")
        self.assertIn(block.encode(), reported)

    def test_repeat_below_threshold_is_ignored(self):
        block = filler("z", 127)
        data = (filler("A", 300) + block + filler("B", 300) + block + filler("C", 300)).encode()
        self.assertEqual([b for b in dedup_check.repeated_blocks(data) if b[0] == block.encode()], [])

    def test_three_occurrences_are_all_reported(self):
        block = filler("REPEATED", 150)
        self.assertEqual(len(block), 150)
        data = (filler("x", 200) + block + filler("y", 200) + block + filler("z", 200) + block).encode()
        self.assertEqual(len(planted(dedup_check.repeated_blocks(data), block, 3)), 1)

    def test_sub_block_covered_by_a_larger_repeat_is_not_reported_twice(self):
        block = filler("COVERING", 256)
        data = (filler("a", 300) + block + filler("b", 300) + block).encode()
        blocks = dedup_check.repeated_blocks(data)
        self.assertEqual(len(blocks), 1, blocks)
        self.assertGreaterEqual(len(blocks[0][0]), 256)
        self.assertIn(block.encode(), blocks[0][0])

    def test_overlapping_run_counts_non_overlapping_occurrences_only(self):
        data = b"m" * 300  # every window overlaps every other
        for block, offsets in dedup_check.repeated_blocks(data):
            starts = sorted(offsets)
            for earlier, later in zip(starts, starts[1:]):
                self.assertGreaterEqual(later - earlier, len(block),
                                        "reported occurrences must not overlap")

    def test_multibyte_utf8_is_handled_on_bytes(self):
        block = "café-雪-" * 24  # multi-byte; >=128 bytes
        self.assertGreaterEqual(len(block.encode()), dedup_check.MIN_BYTES)
        data = (filler("A", 200) + block + filler("B", 200) + block).encode()
        hits = planted(dedup_check.repeated_blocks(data), block, 2)
        self.assertEqual(len(hits), 1)
        # the reporting path must not raise on a preview cut inside a code point
        hits[0][0][:100].decode("utf-8", errors="replace")


class DedupCli(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.mkdtemp()
        self.addCleanup(shutil.rmtree, self.tmp)
        block = filler("DUP", 200)
        data = (filler("head", 400) + block + filler("mid", 400) + block).encode()
        self.run_dir = make_run(self.tmp, {"t1-r2-A.md": data}, {"config": {"tasks": []}})

    def test_help_exits_zero_with_usage(self):
        code, out, _ = run_cli("dedup_check.py", "-h")
        self.assertEqual(code, 0)
        self.assertIn("dedup_check.py <run-dir>", out)

    def test_missing_argument_exits_nonzero(self):
        code, _, err = run_cli("dedup_check.py")
        self.assertNotEqual(code, 0)
        self.assertIn("usage", err.lower())

    def test_run_dir_without_prompts_exits_nonzero(self):
        empty = tempfile.mkdtemp()
        self.addCleanup(shutil.rmtree, empty)
        code, _, err = run_cli("dedup_check.py", empty)
        self.assertNotEqual(code, 0)
        self.assertIn("prompts", err)

    def test_reports_the_planted_duplicate_and_summary(self):
        code, out, _ = run_cli("dedup_check.py", self.run_dir)
        self.assertEqual(code, 0)
        self.assertIn("t1-r2-A.md:", out)
        self.assertRegex(out, r"2\d\d bytes x 2")
        self.assertIn("1 prompts;", out)
        self.assertIn("repeated blocks >=128 bytes", out)

    def test_does_not_modify_the_run_directory(self):
        before = tree_fingerprint(self.run_dir)
        run_cli("dedup_check.py", self.run_dir)
        self.assertEqual(tree_fingerprint(self.run_dir), before)


class SectionAccounting(unittest.TestCase):
    """prompt_report.section_bytes: every byte must land in exactly one section."""

    def setUp(self):
        self.state = {"config": {"tasks": [{"id": "t1", "text": "Do the thing.", "execute": False}]},
                      "answers": []}

    def partition_holds(self, data, state=None):
        counts = prompt_report.section_bytes(data, state or self.state)
        self.assertEqual(sum(counts.values()), len(data),
                         "sections must partition every byte")
        return counts

    def test_partition_holds_for_a_round_prompt(self):
        body, _ = post("Some proposal text.")
        data = prompt_round_n("t1", 2, "t1-c1", "CANDIDATE BODY", [("B", body)])
        counts = self.partition_holds(data)
        self.assertGreater(counts["candidate"], 0)
        self.assertGreater(counts["relayed posts"], 0)

    def test_partition_holds_with_rules_and_notes(self):
        data = ("You are member A of a council of 3 AI agents.\n" + TAIL_RULE +
                "\nHandover note from your predecessor session (same member id):\n"
                "<<<HANDOVER\nnote body\n>>>\n\n"
                "=== TASK t1 {} round 2 of 4 ===\nbody\n\nYour job this round: x\n".format(EM)).encode()
        counts = self.partition_holds(data)
        self.assertGreater(counts["rules"], 0)
        self.assertGreater(counts["replacement notes"], 0)

    def test_candidate_bytes_match_the_candidate_block(self):
        candidate = "CANDIDATE BODY\nsecond line"
        body, _ = post("unrelated")
        data = prompt_round_n("t1", 2, "t1-c1", candidate, [("B", body)])
        counts = prompt_report.section_bytes(data, self.state)
        block = "<<<CANDIDATE t1-c1\n{}\n>>>\n".format(candidate).encode()
        self.assertEqual(counts["candidate"], len(block))

    def test_answers_block_is_attributed_to_answers(self):
        state = dict(self.state, answers=[{"task": "t1", "member": "A",
                                           "question": "Q?", "answer": "A!"}])
        block = (prompt_report.ANSWERS.decode() + "- Q (member A): Q?\n  A: A!\n")
        body, _ = post("unrelated")
        data = prompt_round_n("t1", 2, "t1-c1", "CAND", [("B", body)], answers_block=block)
        counts = self.partition_holds(data, state)
        self.assertEqual(counts["answers"], len(block.encode()))

    def test_quoted_answers_heading_inside_a_post_is_not_an_answers_section(self):
        state = dict(self.state, answers=[{"task": "t1", "member": "A",
                                           "question": "Q?", "answer": "A!"}])
        body, _ = post("I quote: " + prompt_report.ANSWERS.decode() + "- Q (member A): Q?\n  A: A!\n")
        data = prompt_round_n("t1", 2, "t1-c1", "CAND", [("B", body)])
        counts = self.partition_holds(data, state)
        self.assertEqual(counts["answers"], 0, "a member's quotation is member text, not an answers section")

    def test_task_text_counted_only_in_round_one(self):
        text = self.state["config"]["tasks"][0]["text"]
        first = "=== TASK t1 {} round 1 of 4 ===\n{}\n\nYour job this round: x\n".format(EM, text).encode()
        later = "=== TASK t1 {} round 2 of 4 ===\n{}\n\nYour job this round: x\n".format(EM, text).encode()
        self.assertEqual(self.partition_holds(first)["task text"], len(text.encode()))
        self.assertEqual(self.partition_holds(later)["task text"], 0)

    def test_prompt_without_a_task_header_is_all_instructions(self):
        data = b"Your previous reply could not be used: re-send it.\n"
        counts = self.partition_holds(data)
        self.assertEqual(counts["instructions"], len(data))


class MeasureOneReplay(unittest.TestCase):
    """prompt_report.measure_one: the de-duplication saving replay."""

    def setUp(self):
        self.tmp = tempfile.mkdtemp()
        self.addCleanup(shutil.rmtree, self.tmp)
        self.candidate = "CANDIDATE BODY that is long enough to be worth de-duplicating. " * 6
        self.state = {"config": {"tasks": [{"id": "t1", "text": "Do it.", "execute": False}]},
                      "answers": [], "members": [{"id": "A"}, {"id": "B"}],
                      "candidate": {"id": "t1-c1", "member": "A", "text": self.candidate}}

    def build(self, relayed_proposal):
        body, _ = post(relayed_proposal)
        (Path(self.tmp) / "posts").mkdir(parents=True, exist_ok=True)
        (Path(self.tmp) / "posts" / "t1-r1-B.md").write_text(body)
        (Path(self.tmp) / "posts" / "t1-r1-B.json").write_text(
            json.dumps({"vote": "propose", "proposal": relayed_proposal, "questions": []}))
        data = prompt_round_n("t1", 2, "t1-c1", self.candidate, [("B", body)])
        run = make_run(self.tmp, {"t1-r2-A.md": data}, self.state)
        return data, run

    def test_identical_proposal_produces_a_saving_and_keeps_the_text_once(self):
        data, run = self.build(self.candidate)
        after, events = prompt_report.measure_one(data, "t1-r2-A.md", run, self.state)
        self.assertTrue(events, "an exact candidate copy in a relayed post must be de-duplicated")
        saving = sum(e[1] for e in events)
        self.assertGreater(saving, 0)
        self.assertEqual(len(after), len(data) - saving, "reported saving must match the replayed bytes")
        self.assertEqual(after.count(self.candidate.encode()), 1,
                         "the candidate text must survive exactly once")

    def test_different_proposal_is_left_untouched(self):
        data, run = self.build("A completely different proposal. " * 6)
        after, events = prompt_report.measure_one(data, "t1-r2-A.md", run, self.state)
        self.assertEqual(events, [])
        self.assertEqual(after, data)

    def test_one_character_difference_is_not_de_duplicated(self):
        data, run = self.build(self.candidate[:-1] + "!")
        after, events = prompt_report.measure_one(data, "t1-r2-A.md", run, self.state)
        self.assertEqual(events, [], "comparison must be byte-exact")
        self.assertEqual(after, data)


class ReportCli(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.mkdtemp()
        self.addCleanup(shutil.rmtree, self.tmp)
        body, _ = post("proposal")
        data = prompt_round_n("t1", 2, "t1-c1", "CAND BODY", [("B", body)])
        self.state = {"config": {"tasks": [{"id": "t1", "text": "Do it.", "execute": False}]},
                      "answers": [], "members": [{"id": "A"}, {"id": "B"}],
                      "candidate": {"id": "t1-c1", "member": "A", "text": "CAND BODY"}}
        self.run_dir = make_run(self.tmp, {"t1-r2-A.md": data}, self.state)
        (Path(self.tmp) / "posts").mkdir(parents=True, exist_ok=True)
        (Path(self.tmp) / "posts" / "t1-r1-B.md").write_text(body)

    def test_help_exits_zero_with_usage(self):
        code, out, _ = run_cli("prompt_report.py", "-h")
        self.assertEqual(code, 0)
        self.assertIn("prompt_report.py <run-dir>", out)

    def test_missing_state_exits_nonzero(self):
        os.remove(Path(self.run_dir) / "state.json")
        code, _, err = run_cli("prompt_report.py", self.run_dir)
        self.assertNotEqual(code, 0)
        self.assertTrue(err.strip())

    def test_run_without_prompts_exits_nonzero(self):
        empty = tempfile.mkdtemp()
        self.addCleanup(shutil.rmtree, empty)
        (Path(empty) / "state.json").write_text(json.dumps(self.state))
        code, _, err = run_cli("prompt_report.py", empty)
        self.assertNotEqual(code, 0)
        self.assertTrue(err.strip())

    def test_report_prints_totals_and_sections_summing_to_one_hundred(self):
        code, out, _ = run_cli("prompt_report.py", self.run_dir)
        self.assertEqual(code, 0)
        self.assertIn("Prompts:", out)
        percents = [float(line.split()[-1].rstrip("%")) for line in out.splitlines()
                    if line.startswith("  ") and line.rstrip().endswith("%")
                    and any(line.strip().startswith(s.split()[0]) for s in prompt_report.SECTIONS)]
        self.assertAlmostEqual(sum(percents), 100.0, delta=0.05)

    def test_does_not_modify_the_run_directory(self):
        before = tree_fingerprint(self.run_dir)
        run_cli("prompt_report.py", self.run_dir)
        self.assertEqual(tree_fingerprint(self.run_dir), before)


if __name__ == "__main__":
    unittest.main(verbosity=2 if "-v" in sys.argv else 1)
